{% set name = "gpytorch" %}
{% set version = "1.14" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 032cc11e6a46e1e4bc7763fcef318cc830aceaea85a7289f27b2288c7a339a8d

build:
  noarch: python
  number: 0
  script:
    - rm -rf test
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - pytorch >=2.0
    - scikit-learn
    - jaxtyping
    - mpmath >=0.19,<=1.3
    - scipy >=1.6.0
    - linear_operator >=0.6

test:
  imports:
    - gpytorch
    - gpytorch.constraints
    - gpytorch.distributions
    - gpytorch.functions
    - gpytorch.kernels
    - gpytorch.kernels.keops
    - gpytorch.lazy
    - gpytorch.likelihoods
    - gpytorch.means
    - gpytorch.mlls
    - gpytorch.models
    - gpytorch.models.deep_gps
    - gpytorch.models.pyro
    - gpytorch.priors
    - gpytorch.test
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check


about:
  home: https://gpytorch.ai
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of Gaussian Processes in Pytorch
  doc_url: https://pypi.org/project/gpytorch/
  dev_url: https://github.com/cornellius-gp/gpytorch/

extra:
  recipe-maintainers:
    - ngam
    - mxr-conda
    - oblute
    - benhuff
    - AdrianSosic
    - thewchan
