{% set name = "gpytorch" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 896143a070ed73922ff948659e363c5ba562350ab9027a97057edd839c65297e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytorch

test:
  imports:
    - gpytorch
    - gpytorch.constraints
    - gpytorch.distributions
    - gpytorch.functions
    - gpytorch.kernels
    - gpytorch.kernels.keops
    - gpytorch.lazy
    - gpytorch.likelihoods
    - gpytorch.means
    - gpytorch.mlls
    - gpytorch.models
    - gpytorch.models.deep_gps
    - gpytorch.models.pyro
    - gpytorch.priors
    - gpytorch.test
    - test

about:
  home: https://gpytorch.ai
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of Gaussian Processes in Pytorch
  doc_url: https://pypi.org/project/gpytorch/
  dev_url: https://github.com/cornellius-gp/gpytorch/

extra:
  recipe-maintainers:
    - oblute
    - benhuff
