{% set name = "gpytorch" %}
{% set version = "1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f4a488633a2a7a4ab37d12553d1d1dd39690043dbceef14ca428b7d5f89f73ba

build:
  noarch: python
  number: 0
  script:
    - rm -rf test
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
    - setupstools
  run:
    - linear_operator >=0.5.0
    - python >=3.8
    - pytorch >=1.11
    - scikit-learn

test:
  imports:
    - gpytorch
    - gpytorch.constraints
    - gpytorch.distributions
    - gpytorch.functions
    - gpytorch.kernels
    - gpytorch.kernels.keops
    - gpytorch.lazy
    - gpytorch.likelihoods
    - gpytorch.means
    - gpytorch.mlls
    - gpytorch.models
    - gpytorch.models.deep_gps
    - gpytorch.models.pyro
    - gpytorch.priors
    - gpytorch.test
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://gpytorch.ai
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An implementation of Gaussian Processes in Pytorch
  doc_url: https://pypi.org/project/gpytorch/
  dev_url: https://github.com/cornellius-gp/gpytorch/

extra:
  recipe-maintainers:
    - ngam
    - mxr-conda
    - oblute
    - benhuff
    - AdrianSosic
    - thewchan
