schema_version: 1

context:
  name: gpytorch
  version: "1.14.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 8a42f05146f327002b790dd7cb56f1be29f3245d1b0b5128038f2b39111960b0

build:
  number: 0
  noarch: python
  script:
    - rm -rf test
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools_scm
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}
    - jaxtyping
    - mpmath >=0.19,<=1.3
    - scikit-learn
    - scipy >=1.6.0
    - linear_operator >=0.6
    - pytorch >=2.0

tests:
  - python:
      imports:
        - gpytorch
        - gpytorch.constraints
        - gpytorch.distributions
        - gpytorch.functions
        - gpytorch.kernels
        - gpytorch.kernels.keops
        - gpytorch.lazy
        - gpytorch.likelihoods
        - gpytorch.means
        - gpytorch.mlls
        - gpytorch.models
        - gpytorch.models.deep_gps
        - gpytorch.models.pyro
        - gpytorch.priors
        - gpytorch.test
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: An implementation of Gaussian Processes in Pytorch
  homepage: https://gpytorch.ai
  repository: https://github.com/cornellius-gp/gpytorch/
  documentation: https://pypi.org/project/gpytorch/

extra:
  recipe-maintainers:
    - ngam
    - mxr-conda
    - oblute
    - benhuff
    - AdrianSosic
    - thewchan
